matrix:
  - name: Markdown
    sources:
      - '**/*.md'
    dictionary:
      wordlists:
        - .wordlist.txt
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - fenced_code
